/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workspace Open */
        post: operations["workspace_open_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Current */
        get: operations["workspace_current_api_v1_workspaces_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lines */
        get: operations["lines_api_v1_lines_get"];
        put?: never;
        /** Line Create */
        post: operations["line_create_api_v1_lines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lines/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Line Delete */
        delete: operations["line_delete_api_v1_lines__line_id__delete"];
        options?: never;
        head?: never;
        /** Line Patch */
        patch: operations["line_patch_api_v1_lines__line_id__patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_v1_projects_get"];
        put?: never;
        /** Project Create */
        post: operations["project_create_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Project Delete */
        delete: operations["project_delete_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Project Patch */
        patch: operations["project_patch_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pages */
        get: operations["pages_api_v1_pages_get"];
        put?: never;
        /** Page Create */
        post: operations["page_create_api_v1_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page Get */
        get: operations["page_get_api_v1_pages__page_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{page_id}/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Page Confirmation */
        post: operations["page_confirmation_api_v1_pages__page_id__confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{page_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Page Move */
        post: operations["page_move_api_v1_pages__page_id__moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Journal Create */
        post: operations["journal_create_api_v1_journal__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intake List */
        get: operations["intake_list_api_v1_intake_items_get"];
        put?: never;
        /** Intake Text */
        post: operations["intake_text_api_v1_intake_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intake File */
        post: operations["intake_file_api_v1_intake_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Get */
        get: operations["source_get_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intake Job Create */
        post: operations["intake_job_create_api_v1_intake_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intake Job Get */
        get: operations["intake_job_get_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Intake Job Cancel */
        delete: operations["intake_job_cancel_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drafts */
        get: operations["drafts_api_v1_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draft Get */
        get: operations["draft_get_api_v1_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Draft Patch */
        patch: operations["draft_patch_api_v1_drafts__draft_id__patch"];
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Confirmation */
        post: operations["draft_confirmation_api_v1_drafts__draft_id__confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Action Candidates */
        get: operations["action_candidates_api_v1_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index Plan */
        post: operations["index_plan_api_v1_index_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index Execute */
        post: operations["index_execute_api_v1_index_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index Status */
        get: operations["index_status_api_v1_index_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Stream */
        post: operations["query_stream_api_v1_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Query Cancel */
        delete: operations["query_cancel_api_v1_queries__request_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/feishu/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feishu Status */
        get: operations["feishu_status_api_v1_integrations_feishu_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/feishu/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feishu Authorize */
        post: operations["feishu_authorize_api_v1_integrations_feishu_authorizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/feishu/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feishu Callback */
        get: operations["feishu_callback_api_v1_integrations_feishu_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/feishu/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feishu Materials */
        get: operations["feishu_materials_api_v1_integrations_feishu_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/feishu/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feishu Imports */
        post: operations["feishu_imports_api_v1_integrations_feishu_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/feishu/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feishu Calendar */
        get: operations["feishu_calendar_api_v1_integrations_feishu_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionCandidate */
        ActionCandidate: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "todo" | "progress_change";
            /** Description */
            description: string;
            /** Related Project Id */
            related_project_id?: string | null;
            /**
             * State
             * @default proposed
             * @constant
             */
            state: "proposed";
            /**
             * Source Draft Id
             * Format: uuid
             */
            source_draft_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        /** AuthorizationStart */
        AuthorizationStart: {
            /** Authorization Url */
            authorization_url: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** Body_intake_file_api_v1_intake_files_post */
        Body_intake_file_api_v1_intake_files_post: {
            /** Operation Id */
            operation_id: string;
            /** File */
            file: string;
        };
        /** CalendarEvent */
        CalendarEvent: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** CalendarPage */
        CalendarPage: {
            /** Items */
            items: components["schemas"]["CalendarEvent"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Timezone */
            timezone: string;
        };
        /** Draft */
        Draft: {
            /**
             * Draft Id
             * Format: uuid
             */
            draft_id: string;
            /** Input Ids */
            input_ids: string[];
            /** Target Page Id */
            target_page_id?: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Body */
            body: string;
            /** Expected Base Sha256 */
            expected_base_sha256?: string | null;
            /** Important Conflicts */
            important_conflicts?: {
                [key: string]: unknown;
            }[];
            /** Action Suggestions */
            action_suggestions?: {
                [key: string]: unknown;
            }[];
            /** Conflict Resolutions */
            conflict_resolutions?: {
                [key: string]: string;
            };
            /** Source Ids */
            source_ids: string[];
            /**
             * State
             * @default pending
             * @enum {string}
             */
            state: "pending" | "confirmed" | "cancelled";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        } & {
            [key: string]: unknown;
        };
        /** DraftConfirmationRequest */
        DraftConfirmationRequest: {
            /** Expected Version */
            expected_version: number;
            /** Confirmation Id */
            confirmation_id: string;
            /** Operation Id */
            operation_id: string;
            /** Conflict Resolutions */
            conflict_resolutions?: {
                [key: string]: string;
            };
        };
        /** DraftPatchRequest */
        DraftPatchRequest: {
            /** Expected Version */
            expected_version: number;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Target Page Id */
            target_page_id?: string | null;
            /** Expected Base Sha256 */
            expected_base_sha256?: string | null;
        };
        /** FeishuStatus */
        FeishuStatus: {
            /**
             * Mode
             * @default fake
             */
            mode: string;
            /** Authorized */
            authorized: boolean;
            /**
             * Token Type
             * @default user
             */
            token_type: string;
            /** Scopes */
            scopes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportOutcome */
        ImportOutcome: {
            /** Material Id */
            material_id: string;
            /** State */
            state: string;
            /** Item Id */
            item_id?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Message */
            message?: string | null;
        };
        /** ImportRequest */
        ImportRequest: {
            /** Material Ids */
            material_ids: string[];
            /** Operation Id */
            operation_id: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Operation Id */
            operation_id: string;
            /** State */
            state: string;
            /** Outcomes */
            outcomes: components["schemas"]["ImportOutcome"][];
        };
        /** IndexPlan */
        IndexPlan: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "initial" | "incremental" | "full" | "model_change";
            /** Fingerprint */
            fingerprint: string;
            /** Page Ids */
            page_ids: string[];
            /** Page Versions */
            page_versions?: {
                [key: string]: string;
            };
            /** Estimated Tokens */
            estimated_tokens: number;
            /**
             * Estimated Cost
             * @default 0
             */
            estimated_cost: number;
        };
        /** IndexPlanRequest */
        IndexPlanRequest: {
            /** Mode */
            mode: string;
            /** Fingerprint */
            fingerprint: string;
        };
        /** IndexResult */
        IndexResult: {
            /** Indexed Pages */
            indexed_pages: number;
            /** Indexed Chunks */
            indexed_chunks: number;
            /** Embedded Chunks */
            embedded_chunks: number;
            /** Reused Chunks */
            reused_chunks: number;
            /** Active Fingerprint */
            active_fingerprint: string;
            /**
             * Saved Locally
             * @default true
             */
            saved_locally: boolean;
        };
        /** IntakeItem */
        IntakeItem: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Title */
            title: string;
            /** Filename */
            filename: string;
            /** Original Relative Path */
            original_relative_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * State
             * @default pending
             * @enum {string}
             */
            state: "pending" | "processing" | "reviewing" | "completed" | "failed" | "cancelled";
            /** Latest Job Id */
            latest_job_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IntakeJob */
        IntakeJob: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Item Ids */
            item_ids: string[];
            /** Request Hash */
            request_hash: string;
            /**
             * State
             * @enum {string}
             */
            state: "running" | "completed" | "failed" | "cancelled";
            /** Draft Ids */
            draft_ids?: string[];
            /** Action Candidates */
            action_candidates?: {
                [key: string]: unknown;
            }[];
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        /** IntakeJobRequest */
        IntakeJobRequest: {
            /** Item Ids */
            item_ids: string[];
            /** Operation Id */
            operation_id: string;
            /**
             * Line Id
             * Format: uuid
             */
            line_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Reprocess
             * @default false
             */
            reprocess: boolean;
        };
        /** IntakeTextRequest */
        IntakeTextRequest: {
            /** Text */
            text: string;
            /**
             * Filename
             * @default paste.txt
             */
            filename: string;
            /** Operation Id */
            operation_id: string;
        };
        /** JournalRequest */
        JournalRequest: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Line Id */
            line_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Confirmation Id */
            confirmation_id: string;
            /** Operation Id */
            operation_id: string;
        };
        /** LineCreate */
        LineCreate: {
            /** Name */
            name: string;
            /** Operation Id */
            operation_id: string;
        };
        /** LinePatch */
        LinePatch: {
            /** Name */
            name: string;
            /** Operation Id */
            operation_id: string;
        };
        /** LineRecord */
        LineRecord: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Directory */
            directory: string;
        } & {
            [key: string]: unknown;
        };
        /** Material */
        Material: {
            /** Material Id */
            material_id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @default minute
             * @constant
             */
            kind: "minute";
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "owner" | "shared";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MaterialPage */
        MaterialPage: {
            /** Items */
            items: components["schemas"]["Material"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** MutationResult */
        MutationResult: {
            /** Operation Id */
            operation_id: string;
            /**
             * State
             * @default succeeded
             * @constant
             */
            state: "succeeded";
            /** Changed Paths */
            changed_paths: string[];
            /** Page Versions */
            page_versions?: {
                [key: string]: string;
            };
            /**
             * Saved Locally
             * @default true
             */
            saved_locally: boolean;
        };
        /** PageConfirmation */
        PageConfirmation: {
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Body */
            body: string;
            /** Confirmation Id */
            confirmation_id: string;
            /** Operation Id */
            operation_id: string;
            /** Expected Base Sha256 */
            expected_base_sha256: string;
        };
        /** PageCreate */
        PageCreate: {
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Body */
            body: string;
            /** Confirmation Id */
            confirmation_id: string;
            /** Operation Id */
            operation_id: string;
        };
        /** PageMove */
        PageMove: {
            /** Destination Relative Path */
            destination_relative_path: string;
            /** Operation Id */
            operation_id: string;
            /** Structure Confirmation Id */
            structure_confirmation_id?: string | null;
        };
        /** PageSnapshot */
        PageSnapshot: {
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /** Relative Path */
            relative_path: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Body */
            body: string;
            /** Content Sha256 */
            content_sha256: string;
            /**
             * Storage Area
             * @enum {string}
             */
            storage_area: "formal" | "source" | "draft" | "system";
            /**
             * Approval State
             * @enum {string}
             */
            approval_state: "confirmed" | "pending" | "invalid";
            /**
             * Validity
             * @default current
             */
            validity: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Line Id
             * Format: uuid
             */
            line_id: string;
            /** Name */
            name: string;
            /** Operation Id */
            operation_id: string;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Name */
            name?: string | null;
            /** Archived */
            archived?: boolean | null;
            /** Operation Id */
            operation_id: string;
        };
        /** ProjectRecord */
        ProjectRecord: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Line Id
             * Format: uuid
             */
            line_id: string;
            /** Name */
            name: string;
            /** Directory */
            directory: string;
            /**
             * Overview Id
             * Format: uuid
             */
            overview_id: string;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
        } & {
            [key: string]: unknown;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Purpose
             * @default current
             * @enum {string}
             */
            purpose: "current" | "history";
            /** Request Id */
            request_id?: string | null;
        };
        /** SourceDetail */
        SourceDetail: {
            source: components["schemas"]["SourceRecord"];
            /** Text */
            text: string;
        };
        /** SourceRecord */
        SourceRecord: {
            /** External Identity */
            external_identity?: {
                [key: string]: string;
            } | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Role
             * @default source
             * @constant
             */
            role: "source";
            /** Original Relative Path */
            original_relative_path: string;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceContext */
        WorkspaceContext: {
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Root */
            root: string;
            /** Local Profile Dir */
            local_profile_dir: string;
            /** Name */
            name: string;
            /**
             * Read Only
             * @default false
             */
            read_only: boolean;
        };
        /** WorkspaceRequest */
        WorkspaceRequest: {
            /** Root */
            root: string;
            /** Mode */
            mode: string;
            /** Name */
            name?: string | null;
            /** Operation Id */
            operation_id: string;
        };
        /** Citation */
        Citation: {
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Chunk Id */
            chunk_id: string;
            /** Heading */
            heading: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Validity
             * @default current
             * @enum {string}
             */
            validity: "current" | "superseded" | "invalid";
        };
        /** Answer */
        Answer: {
            /**
             * Answer Id
             * Format: uuid
             */
            answer_id: string;
            /** Question */
            question: string;
            /** Text */
            text: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Inferences */
            inferences?: string[];
            /** Missing Information */
            missing_information?: string[];
            /**
             * Purpose
             * @default current
             * @enum {string}
             */
            purpose: "current" | "history";
            /**
             * Index Status
             * @enum {string}
             */
            index_status: "ready" | "empty" | "not_ready";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    workspace_open_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_current_api_v1_workspaces_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lines_api_v1_lines_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    line_create_api_v1_lines_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    line_delete_api_v1_lines__line_id__delete: {
        parameters: {
            query: {
                operation_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    line_patch_api_v1_lines__line_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_create_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_delete_api_v1_projects__project_id__delete: {
        parameters: {
            query: {
                operation_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_patch_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pages_api_v1_pages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_create_api_v1_pages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_get_api_v1_pages__page_id__get: {
        parameters: {
            query?: {
                expected_content_sha256?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_confirmation_api_v1_pages__page_id__confirmations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_move_api_v1_pages__page_id__moves_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    journal_create_api_v1_journal__kind__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                kind: "log" | "thought";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_list_api_v1_intake_items_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_text_api_v1_intake_items_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_file_api_v1_intake_files_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_intake_file_api_v1_intake_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_get_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_job_create_api_v1_intake_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_job_get_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intake_job_cancel_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drafts_api_v1_drafts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_get_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_patch_api_v1_drafts__draft_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_confirmation_api_v1_drafts__draft_id__confirmations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_candidates_api_v1_actions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionCandidate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_plan_api_v1_index_plans_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_execute_api_v1_index_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexPlan"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_status_api_v1_index_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_stream_api_v1_queries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_cancel_api_v1_queries__request_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_status_api_v1_integrations_feishu_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_authorize_api_v1_integrations_feishu_authorizations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationStart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_callback_api_v1_integrations_feishu_callback_get: {
        parameters: {
            query: {
                state: string;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_materials_api_v1_integrations_feishu_materials_get: {
        parameters: {
            query?: {
                query?: string;
                visibility?: ("owner" | "shared") | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_imports_api_v1_integrations_feishu_imports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_calendar_api_v1_integrations_feishu_calendar_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                timezone: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
